repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: pytest -v
        always_run: true
        pass_filenames: false
        stages: [commit]
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: pip freeze > requeriments.txt; git add requirements.txt
        language: system
        pass_filenames: false
        stages: [commit]